package gogen

// ResourceContainer encapsulates behavior of any content
// that is generated by the generators. This allows
// generators to communicate when in pipelines
type ResourceContainer []interface{}

// Add will append the value to the end of the resource
// container.
func (rc *ResourceContainer) Add(v interface{}) {
	(*rc) = append((*rc), v)
}
